### ISSUE TITLE
UI Problem when porting OpenBoard to Fedora 30

### ISSUE THREAD

**Issue by hansbothe** [OpenBoard-org/OpenBoard-ThirdParty#2]
~/OpenBoard/resources/forms/trapFlash.ui line 116:
    <header>QtWebKit/QWebView</header>

was changed to:
    <header>QtWebKit</header>

Afterwards OpenBoard compiled, linked and run just nicely under Fedora 30. Testing the system now. Sorry for issuing a problem prematurely. It would be nice if somebody could point out the consequences of my change to permanently apply a fix.

**Comment by kaamui** [comment]
Hello

Thank you for your help. A similar patch had to be applied during the porting of OpenBoard from qt5.5 to qt5.13. The work for this porting is done in the dev-qt5.1x branch.
